packages:
  - "apps/*"
  - "libs/*"
  - "libs/shared/*"
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "core-js"
  - "core-js-pure"
  - "cypress"
  - "esbuild"
  - "nx"
  - "sharp"
  - "unrs-resolver"
